# Generated by Django 4.1.4 on 2022-12-09 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='User',
        ),
    ]
