# Generated by Django 4.1.6 on 2023-02-10 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_rename_results_stresults_rslt'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stresults',
            table=None,
        ),
    ]
