# Generated by Django 4.1.6 on 2023-02-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_alter_user_managers_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
