# Generated by Django 4.1.6 on 2023-02-11 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0013_remove_user_session_key_loggedinuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loggedinuser',
            options={'permissions': [('logout', 'Logout user sessions in bulk for a given user.'), ('logout_all', 'Logout user sessions in bulk for a given (admin) user.')]},
        ),
        migrations.RemoveField(
            model_name='loggedinuser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='loggedinuser',
            name='session_key',
        ),
        migrations.AddField(
            model_name='loggedinuser',
            name='session',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='usersessions', related_query_name='usersession', serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loggedinuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
