# Generated by Django 4.1.6 on 2023-02-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_alter_loggedinuser_options_remove_loggedinuser_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoggedInUser',
        ),
    ]
